version: "3"
services:

  bot-ai:
    container_name: bot-ai
    build:
      context: ./bot-ai
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    command: npm run start:dev
    volumes:
      - ./bot-ai:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    hostname: mongo
    env_file:
      - ./bot-ai/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${HOST_MONGO_DB}:${MONGO_DB_PORT}/
    depends_on:
      - mongo

volumes:
  mongodb_data_volume:
    driver: local
